development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: christmas_in_hull_2012
  pool: 5
  username: root
  password: tmedia
  host: 192.168.0.122
  #socket: /tmp/mysql.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: christmas_in_hull_2012_production
  pool: 5
  username: christ
  password: xmas47#!
#  socket: /tmp/mysql.sock
